/** Product chrome copy for Quest — not business magic numbers. */

export const QUEST_COPY = {
  pathsTitle: "Pick your plan",
  pathsSubtitle: "One plan at a time. Built from your answers and focus areas.",
  pathsSubtitleMobile: "Swipe to compare plans below.",
  startPlan: "Start this plan",
  resumePlan: "Resume plan",
  lockedPlan: "Locked",
  activeBadge: "Active plan",
  solvesLabel: "Focuses",
  viewPlan: "View plan",
  seeDetails: "See details",
  planBenefits: "Plan benefits",
  swipeHint: "Swipe to compare plans",
  confirmStartTitle: "Start this plan?",
  confirmStart: (weeks: number) =>
    `You'll commit to this ${weeks}-week plan. Other plans stay locked until you complete or abandon this one.`,
  confirmStartConfirm: "Start plan",
  confirmStartCancel: "Cancel",
  missionThisWeek: "This week",
  missionRoadmap: "Full roadmap",
  missionWeekOf: (current: number, total: number) => `Week ${current} of ${total}`,
  planProgress: "Plan progress",
  checkInsCount: (done: number, total: number) => `${done} / ${total} weekly check-ins`,
  checkInDue: (week: number) => `Week ${week} check-in ready`,
  checkInCta: "Log weekly check-in",
  checkInTitle: (week: number) => `Week ${week} check-in`,
  checkInPulse: "How did money feel this week?",
  checkInSave: "Save check-in",
  checkInCancel: "Not now",
  thisWeekLogged: (week: number) => `Week ${week} check-in logged`,
  checkInNotDue: "Focus on this week’s actions. Check-in unlocks when the week is ready.",
  checkInComplete: "All weekly check-ins are complete.",
  reviewPrompt: "Time for a progress review — refresh your numbers to see if focuses moved.",
  reviewCta: "Go refresh data",
  chartTitle: "Projected impact if you hit the plan target",
  chartLocked: "Log a check-in to unlock the projection chart.",
  abandonHint: "Goal shifted? You can generate new suggestions after the cooldown.",
  generateNew: "Generate new suggestions",
  targetLabel: (amount: number) =>
    `Target: +₹${amount.toLocaleString("en-IN")}/mo toward the plan`,
  deltaTitle: "Focus movement since you started",
  noDeltaYet: "Refresh your financial data after a review week to see deltas.",
} as const;
